#Chile - Universidad Adolfo Ibáñez (UAI)
##Curso NLP
### Prediction-based Word Embeddings

# Spanish Pipeline (Small)

In [ ]:
#Importar Librerías
import spacy
import numpy as np

In [ ]:
#Cargar Data
data = [
        "Mi mamá ama las manzanas",
        "Katy Perry odia las manzanas.",
        "Orlando Bloom compró acciones en NotCo",
        "Mi hermana nació en Melipilla",
        "Katy Perry visitó Melipilla",
        "Los fundadores de NotCo nacieron en Melipilla",
        "No me gustó la comida en Melipilla",
        "Orlando Bloom compró una casa en Melipilla",
        "Mi postulación a NotCo fue rechazada",
        "Mi papá fue al colegio en Melipilla",
        "El que fue a Melipilla perdió su silla",
        "No me gustan los productos de NotCo",
        "Anoche hubieron protestas contra NotCo"
        ]

In [ ]:
#Descargar Pipeline (Spanish)
!python -m spacy download es_core_news_sm -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 67.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
#Cargar Pipeline
nlp_sm = spacy.load("es_core_news_sm")

In [ ]:
#Crear Doc Object
doc_sm = nlp_sm(data[0])

In [ ]:
#Validar Existencia Word Embeddings (word2vec)
for token in doc_sm:
  print(token.text, "---", token.has_vector)

Mi --- True
mamá --- True
ama --- True
las --- True
manzanas --- True


In [ ]:
#Revisar Representación Vectorial (Token)
print("Dimensionalidad Word Embeddings (Token):", doc_sm[0].vector.shape)
doc_sm[0].vector

Dimensionalidad Word Embeddings (Token): (96,)


array([ 6.9892406e-03,  1.0077634e+00, -3.8158053e-01, -1.1402383e+00,
       -7.8406692e-01, -3.6245937e+00,  2.1512282e+00,  5.3614414e-01,
        2.6875980e+00,  1.0427898e+00, -1.3940706e+00,  1.1194376e+00,
        3.7582450e+00,  6.5327710e-01, -1.3384073e+00,  1.1492132e+00,
        3.5075905e+00,  2.0767889e+00,  7.8509474e-01, -3.0588040e+00,
        1.2918670e+00,  3.6153998e+00, -1.6605558e+00, -3.2527642e+00,
       -9.7864032e-02, -2.4871712e+00, -1.1237750e+00, -1.2653329e+00,
        2.3063331e+00,  4.7394371e+00,  1.6611922e+00,  2.1163228e+00,
       -1.3485646e-01,  4.8707587e-01, -1.4911772e+00,  1.4092398e+00,
       -4.5422095e-01, -4.2417679e+00,  9.3896747e-02, -1.2741697e+00,
        1.4715223e+00, -1.2422969e+00, -4.7737951e+00, -1.1458102e+00,
       -2.6464148e+00, -4.0623924e-01, -3.0515237e+00, -1.6433133e+00,
       -1.0683662e+00,  4.0203514e+00,  4.3796530e+00,  1.2309690e+00,
        3.0495446e+00,  4.0052047e-01, -1.1480861e+00,  1.3892033e+00,
      

In [ ]:
#Revisar Representación Vectorial (Documento - Promedio Simple)
print("Dimensionalidad Word Embeddings (Documento):", doc_sm.vector.shape)
doc_sm.vector

Dimensionalidad Word Embeddings (Documento): (96,)


array([ 0.23847179,  0.83143175, -0.08286581, -0.00640143, -1.1934675 ,
       -1.8731153 ,  1.602158  ,  0.4682359 , -0.22379157,  0.7092519 ,
        0.25375143,  0.5063567 ,  1.0522606 ,  0.40602407, -1.2394956 ,
        0.4970673 ,  1.1260221 ,  0.8392974 , -1.2993717 , -1.9064556 ,
        0.47236538,  1.3806236 ,  0.34319884, -1.8141508 ,  0.34913272,
       -1.4599904 ,  0.92621577, -0.09451339,  0.06188852,  1.4088356 ,
        1.2058424 , -0.6406418 , -0.69434035,  0.3636872 ,  0.23446357,
       -0.14876406, -1.1247209 , -0.90146446,  1.3096902 , -0.4434902 ,
        0.26374158,  0.25972122, -0.8798312 ,  1.2987999 ,  0.15523729,
        0.97351897, -0.03881744,  0.35072565, -1.0899712 , -0.38380915,
        0.59741163,  0.49960485,  1.0935731 , -0.19576982, -2.1334734 ,
        0.39193398,  1.7560333 , -0.6667274 , -0.4048923 , -1.2405741 ,
       -1.1249464 ,  1.2250121 , -1.7940258 , -0.17673135, -1.8303016 ,
        1.2295411 , -0.9208115 , -1.6538826 , -0.52416056, -1.08

In [ ]:
#Crear Representación Vectorial para Set Documentos
X_sm = list()
for text in data:
  X_sm.append(nlp_sm(text).vector)

In [ ]:
#Convertir Lista en Numpy Array
X_sm = np.array(X_sm)
print("Dimensionalidad Rep. Vectorial:", X_sm.shape)

Dimensionalidad Rep. Vectorial: (13, 96)


# Spanish Pipeline (Medium)

In [ ]:
#Descargar Pipeline (English)
!python -m spacy download es_core_news_md -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 MB 19.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
#Cargar Pipeline
nlp_md = spacy.load("es_core_news_md")

In [ ]:
#Crear Doc Object
doc_md = nlp_md(data[0])

In [ ]:
#Revisar Representación Vectorial (Token)
print("Dimensionalidad Word Embeddings (Token):", doc_md[0].vector.shape)
doc_md[0].vector

Dimensionalidad Word Embeddings (Token): (300,)


array([-1.9404e+00,  1.9105e+00, -9.3088e+00,  1.3549e+00,  4.1000e+00,
       -1.9104e-01, -2.2157e+00,  2.5863e-01,  2.1628e+00, -9.4065e+00,
        4.1135e+00, -3.8849e+00, -2.7939e+00, -3.0468e+00, -1.7454e+00,
        5.5956e-02,  9.9157e+00, -5.5204e+00,  3.4488e+00, -1.0240e+00,
       -8.0252e+00, -4.6070e+00,  5.2104e+00,  3.6452e+00, -3.2765e+00,
        1.2593e+00, -1.0383e+00, -1.2450e+00, -3.0145e+00,  1.2102e+01,
       -2.2211e+00,  6.2293e+00,  7.1747e+00, -5.9971e-01,  9.8436e+00,
        1.5869e+00,  1.5318e-01,  6.5774e+00, -9.9527e-01, -5.6178e+00,
        2.1957e+00, -1.7272e+00, -1.6804e+00, -5.4881e-01,  1.3629e+01,
       -6.9420e-01, -6.5158e-01,  1.4769e+01, -4.6708e+00, -2.1389e+00,
        2.8142e+00,  4.1257e+00, -5.6887e-03,  1.9842e+00,  3.5662e+00,
        2.6484e+00,  1.9626e+00, -8.1521e+00, -2.6347e+00, -5.0689e+00,
        7.0462e+00, -4.1781e+00,  1.0387e+00,  6.2273e+00,  1.7876e+00,
       -7.1278e+00, -2.3332e+00, -1.9547e+00,  3.8839e+00,  5.79

In [ ]:
#Revisar Representación Vectorial (Documento - Promedio Simple)
print("Dimensionalidad Word Embeddings (Documento Completo):", doc_md.vector.shape)
doc_md.vector

Dimensionalidad Word Embeddings (Documento Completo): (300,)


array([-3.73145789e-02,  1.11617398e+00, -2.27069974e+00,  1.27130806e+00,
        4.44750023e+00, -1.44018805e+00, -1.46512508e+00,  9.62662041e-01,
       -3.74112219e-01,  3.24720234e-01, -7.45649934e-01, -1.62231612e+00,
       -1.31675136e+00, -8.57125938e-01, -2.11243200e+00, -1.65153289e+00,
        1.12183797e+00, -1.47405791e+00,  1.16760409e+00, -1.01790786e+00,
       -1.64601588e+00, -8.95667911e-01,  2.08914208e+00,  1.60221887e+00,
       -1.14509010e+00, -1.04997802e+00, -1.79203391e+00, -7.34925926e-01,
        6.44540012e-01,  4.02600193e+00,  1.45374203e+00,  4.91696030e-01,
        1.94976211e+00, -1.57360804e+00,  1.83575594e+00,  5.81106782e-01,
       -9.70035553e-01,  7.88300037e-01, -1.69487998e-01,  1.10347998e+00,
       -1.39476225e-01, -1.27673411e+00, -2.50613987e-01, -5.94108582e-01,
        3.23211408e+00, -4.72797692e-01, -1.41617990e+00,  2.93653989e+00,
       -8.36840272e-01, -4.92612600e-01, -1.17944017e-01,  4.27856028e-01,
       -1.26845747e-01,  